/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ml_rabidbeaver_cupsjni_CupsClient */

#ifndef _Included_ml_rabidbeaver_cupsjni_CupsClient
#define _Included_ml_rabidbeaver_cupsjni_CupsClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ml_rabidbeaver_cupsjni_CupsClient
 * Method:    cupsGetDestWithURI
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Lml/rabidbeaver/cupsjni/CupsClient/cups_dest_t;
 */
JNIEXPORT jobject JNICALL Java_ml_rabidbeaver_cupsjni_CupsClient_cupsGetDestWithURI
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class ml_rabidbeaver_cupsjni_CupsClient_cups_dest_t */

#ifndef _Included_ml_rabidbeaver_cupsjni_CupsClient_cups_dest_t
#define _Included_ml_rabidbeaver_cupsjni_CupsClient_cups_dest_t
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class ml_rabidbeaver_cupsjni_CupsClient_cups_option_t */

#ifndef _Included_ml_rabidbeaver_cupsjni_CupsClient_cups_option_t
#define _Included_ml_rabidbeaver_cupsjni_CupsClient_cups_option_t
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
