package ml.rabidbeaver.jna;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : /home/adam/git/CupsClientService/jni/cups-2.0.2/cups/cups.h:53</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class cups_option_s extends Structure {
	/**
	 * Name of option<br>
	 * C type : char*
	 */
	public Pointer name;
	/**
	 * Value of option<br>
	 * C type : char*
	 */
	public Pointer value;
	public cups_option_s() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("name", "value");
	}
	/**
	 * @param name Name of option<br>
	 * C type : char*<br>
	 * @param value Value of option<br>
	 * C type : char*
	 */
	public cups_option_s(Pointer name, Pointer value) {
		super();
		this.name = name;
		this.value = value;
	}
	public cups_option_s(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends cups_option_s implements Structure.ByReference {
		
	};
	public static class ByValue extends cups_option_s implements Structure.ByValue {
		
	};
}
