package ml.rabidbeaver.jna;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : /home/adam/git/CupsClientService/jni/cups-2.0.2/cups/cups.h:60</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class cups_dest_s extends Structure {
	/**
	 * Printer or class name<br>
	 * C type : char*
	 */
	public Pointer name;
	/**
	 * Printer or class name<br>
	 * C type : char*
	 */
	public Pointer instance;
	/** Is this printer the default? */
	public int is_default;
	/** Number of options */
	public int num_options;
	/**
	 * Options<br>
	 * C type : cups_option_t*
	 */
	public ml.rabidbeaver.jna.cups_option_s.ByReference options;
	public cups_dest_s() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("name", "instance", "is_default", "num_options", "options");
	}
	/**
	 * @param name Printer or class name<br>
	 * C type : char*<br>
	 * @param instance Printer or class name<br>
	 * C type : char*<br>
	 * @param is_default Is this printer the default?<br>
	 * @param num_options Number of options<br>
	 * @param options Options<br>
	 * C type : cups_option_t*
	 */
	public cups_dest_s(Pointer name, Pointer instance, int is_default, int num_options, ml.rabidbeaver.jna.cups_option_s.ByReference options) {
		super();
		this.name = name;
		this.instance = instance;
		this.is_default = is_default;
		this.num_options = num_options;
		this.options = options;
	}
	public cups_dest_s(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends cups_dest_s implements Structure.ByReference {
		
	};
	public static class ByValue extends cups_dest_s implements Structure.ByValue {
		
	};
}
