package ml.rabidbeaver.jna;
import com.ochafik.lang.jnaerator.runtime.NativeSize;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : /home/adam/git/CupsClientService/jni/cups-2.0.2/cups/http.h:188</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class http_credential_s extends Structure {
	/**
	 * Pointer to credential data<br>
	 * C type : void*
	 */
	public Pointer data;
	/** Credential length */
	public NativeSize datalen;
	public http_credential_s() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("data", "datalen");
	}
	/**
	 * @param data Pointer to credential data<br>
	 * C type : void*<br>
	 * @param datalen Credential length
	 */
	public http_credential_s(Pointer data, NativeSize datalen) {
		super();
		this.data = data;
		this.datalen = datalen;
	}
	public http_credential_s(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends http_credential_s implements Structure.ByReference {
		
	};
	public static class ByValue extends http_credential_s implements Structure.ByValue {
		
	};
}
