package ml.rabidbeaver.jna;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : /home/adam/git/CupsClientService/jni/cups-2.0.2/cups/http.h:179</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class http_addrlist_s extends Structure {
	/**
	 * Pointer to next address in list<br>
	 * C type : http_addrlist_s*
	 */
	public http_addrlist_s.ByReference next;
	/**
	 * Address<br>
	 * C type : http_addr_t
	 */
	public http_addr_t addr;
	public http_addrlist_s() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("next", "addr");
	}
	/**
	 * @param next Pointer to next address in list<br>
	 * C type : http_addrlist_s*<br>
	 * @param addr Address<br>
	 * C type : http_addr_t
	 */
	public http_addrlist_s(http_addrlist_s.ByReference next, http_addr_t addr) {
		super();
		this.next = next;
		this.addr = addr;
	}
	public http_addrlist_s(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends http_addrlist_s implements Structure.ByReference {
		
	};
	public static class ByValue extends http_addrlist_s implements Structure.ByValue {
		
	};
}
