package ml.rabidbeaver.jna;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : /home/adam/git/CupsClientService/jni/cups-2.0.2/cups/pwg.h:21</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class pwg_size_s extends Structure {
	/**
	 * Map element<br>
	 * C type : pwg_map_t
	 */
	public pwg_map_s map;
	/** Width in 2540ths */
	public int width;
	/** Width in 2540ths */
	public int length;
	/** Width in 2540ths */
	public int left;
	/** Width in 2540ths */
	public int bottom;
	/** Width in 2540ths */
	public int right;
	/** Width in 2540ths */
	public int top;
	public pwg_size_s() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("map", "width", "length", "left", "bottom", "right", "top");
	}
	/**
	 * @param map Map element<br>
	 * C type : pwg_map_t<br>
	 * @param width Width in 2540ths<br>
	 * @param length Width in 2540ths<br>
	 * @param left Width in 2540ths<br>
	 * @param bottom Width in 2540ths<br>
	 * @param right Width in 2540ths<br>
	 * @param top Width in 2540ths
	 */
	public pwg_size_s(pwg_map_s map, int width, int length, int left, int bottom, int right, int top) {
		super();
		this.map = map;
		this.width = width;
		this.length = length;
		this.left = left;
		this.bottom = bottom;
		this.right = right;
		this.top = top;
	}
	public pwg_size_s(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends pwg_size_s implements Structure.ByReference {
		
	};
	public static class ByValue extends pwg_size_s implements Structure.ByValue {
		
	};
}
