package ml.rabidbeaver.jna;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : /home/adam/git/CupsClientService/jni/cups-2.0.2/cups/pwg.h:5</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class pwg_map_s extends Structure {
	/**
	 * PWG media keyword<br>
	 * C type : char*
	 */
	public Pointer pwg;
	/**
	 * PWG media keyword<br>
	 * C type : char*
	 */
	public Pointer ppd;
	public pwg_map_s() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("pwg", "ppd");
	}
	/**
	 * @param pwg PWG media keyword<br>
	 * C type : char*<br>
	 * @param ppd PWG media keyword<br>
	 * C type : char*
	 */
	public pwg_map_s(Pointer pwg, Pointer ppd) {
		super();
		this.pwg = pwg;
		this.ppd = ppd;
	}
	public pwg_map_s(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends pwg_map_s implements Structure.ByReference {
		
	};
	public static class ByValue extends pwg_map_s implements Structure.ByValue {
		
	};
}
